### ISSUE TITLE
aip list causes exception on MacOS Catalina

### ISSUE THREAD

**Issue by sglebs** [Seeed-Studio/ArduPy#13]
```
python3 --version
Python 3.7.8

pip3 install ardupy-aip
```

```
aip list
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'update time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aip", line 5, in <module>
    from aip.main import main
  File "/usr/local/lib/python3.7/site-packages/aip/main.py", line 39, in <module>
    from aip.parser import parser
  File "/usr/local/lib/python3.7/site-packages/aip/parser.py", line 465, in <module>
    parser = Parser()
  File "/usr/local/lib/python3.7/site-packages/aip/parser.py", line 70, in __init__
    self.check_board_version()
  File "/usr/local/lib/python3.7/site-packages/aip/parser.py", line 99, in check_board_version
    time = self.cp.get('board', 'update time')
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'update time' in section: 'board'
```

**Comment by LynnL4** [comment]
Please try to empty the aip directory and execute AIP.
```/ users / [username] /. Config / AIP```
